version: "3.9"
services:
  api:
    build: 
        context: .
        dockerfile: ./source/PlantTelemetryApp.Web/Dockerfile
    ports:
      - 8080:80
    environment:
      - ConnectionStrings__Database=Server=db;Database=master;User=sa;Password=P@ssword;
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server
    ports:
     - 1433:1433
    environment:
      SA_PASSWORD: "P@ssword"
      ACCEPT_EULA: "Y"