name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
     
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout 
        
      - uses: docker/login-action@v2
        name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
      - uses: docker/setup-buildx-action@v2
        name: Set up Docker Buildx
        
      - uses: docker/build-push-action@v3
        name: Build and push
        with:
          context: .
          file: source/PlantTelemetryApp.Web/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/plant-telemetry-app:latest
          
